### ISSUE TITLE
Could not find AZ z2 (deploy error)

### ISSUE THREAD

**Issue by bodymindarts** [genesis-community/vault-genesis-kit#1]
```
genesis deploy play-proto.yml
1 error(s) detected:
 - $.instance_groups.vault.networks.0.static_ips: could not find AZ z2 (in network AZS [z1 z2 z3])
```
This is the vault network in the cloud config:
```
networks:
- name: vault
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    reserved:
    - 10.0.1.0-10.0.1.15
    - 10.0.1.32-10.0.1.255
    azs: [z1, z2, z3]
    cloud_properties:
      network_name: play
      subnetwork_name: play-proto
      tags: [bosh-agent, vault]
```
